# Generated by Django 5.1.6 on 2025-06-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminModel",
            fields=[
                (
                    "adminEmailId",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("adminPassword", models.CharField(max_length=100)),
                ("adminName", models.CharField(max_length=100)),
                ("adminPhoneno", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("FirstName", models.CharField(max_length=100)),
                ("LastName", models.CharField(max_length=100)),
                (
                    "EmailId",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("PhoneNo", models.CharField(max_length=100, unique=True)),
                ("Password", models.CharField(max_length=100)),
            ],
        ),
    ]
